package io.github.junxworks.ep.fs.entity;

import java.util.Date;

import io.github.junxworks.ep.core.orm.annotations.Column;
import io.github.junxworks.ep.core.orm.annotations.PrimaryKey;
import io.github.junxworks.ep.core.orm.annotations.Table;

/**
 * <p>Entity Class</p>
 * <p>Table: sys_file_thumb</p>
 *
 * @since 2020-6-4 13:58:07 Generated by JunxPlugin
 */

@Table(tableName = "s_file_thumb", tableComment = "")
public class SFileThumb {

	@PrimaryKey
	@Column(name = "id", type = "VARCHAR", length = "50", nullable = "false", comment = "主键")
	private String id;

	@Column(name = "fileId", type = "VARCHAR", length = "50", nullable = "false", comment = "")
	private String fileId;

	@Column(name = "width", type = "INTEGER", length = "10", nullable = "false", comment = "")
	private Integer width;

	@Column(name = "height", type = "INTEGER", length = "10", nullable = "false", comment = "")
	private Integer height;

	@Column(name = "file_size", type = "BIGINT", length = "19", nullable = "false", comment = "文件大小")
	private Long fileSize;

	@Column(name = "file_extension", type = "VARCHAR", length = "20", nullable = "true", comment = "文件扩展名")
	private String fileExtension;

	@Column(name = "storage_id", type = "VARCHAR", length = "100", nullable = "false", comment = "文件存储id，通过这个id取获取")
	private String storageId;

	@Column(name = "storage_driver", type = "VARCHAR", length = "100", nullable = "false", comment = "存储驱动名，后台程序记录，可用于问题分析")
	private String storageDriver;

	@Column(name = "create_time", type = "TIMESTAMP", length = "19", nullable = "false", comment = "创建时间")
	private Date createTime;

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getFileId() {
		return fileId;
	}

	public void setFileId(String fileId) {
		this.fileId = fileId;
	}

	public Integer getWidth() {
		return this.width;
	}

	public void setWidth(Integer width) {
		this.width = width;
	}

	public Integer getHeight() {
		return this.height;
	}

	public void setHeight(Integer height) {
		this.height = height;
	}

	public Long getFileSize() {
		return this.fileSize;
	}

	public void setFileSize(Long fileSize) {
		this.fileSize = fileSize;
	}

	public String getFileExtension() {
		return this.fileExtension;
	}

	public void setFileExtension(String fileExtension) {
		this.fileExtension = fileExtension;
	}

	public String getStorageId() {
		return this.storageId;
	}

	public void setStorageId(String storageId) {
		this.storageId = storageId;
	}

	public String getStorageDriver() {
		return this.storageDriver;
	}

	public void setStorageDriver(String storageDriver) {
		this.storageDriver = storageDriver;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}
}