package io.github.junxworks.ep.sys.entity;

import io.github.junxworks.ep.core.orm.annotations.Table;
import io.github.junxworks.ep.core.orm.annotations.PrimaryKey;
import io.github.junxworks.ep.core.orm.annotations.Column;
import java.util.Date;

/**
 * <p>Entity Class</p>
 * <p>Table: ep_s_top_item</p>
 *
 * @since 2021年9月9日 下午7:33:34 Generated by JunxPlugin
 */

@Table(tableName = "ep_s_top_item", tableComment = "")
public class EpSTopItem {

	@PrimaryKey
	@Column(name = "id", type = "BIGINT", length = "19", nullable = "false", comment = "")
	private Long id;

	@Column(name = "create_date", type = "TIMESTAMP", length = "19", nullable = "true", comment = "")
	private Date createDate;

	@Column(name = "create_user", type = "BIGINT", length = "19", nullable = "true", comment = "")
	private Long createUser;

	@Column(name = "update_date", type = "TIMESTAMP", length = "19", nullable = "true", comment = "")
	private Date updateDate;

	@Column(name = "update_user", type = "BIGINT", length = "19", nullable = "true", comment = "")
	private Long updateUser;

	@Column(name = "item_name", type = "VARCHAR", length = "20", nullable = "true", comment = "组件名称")
	private String itemName;

	@Column(name = "item_index", type = "INTEGER", length = "10", nullable = "true", comment = "菜单位置 越小越靠左")
	private Integer itemIndex;

	@Column(name = "item_inner_html", type = "VARCHAR", length = "2,000", nullable = "true", comment = "渲染的内部html")
	private String itemInnerHtml;

	@Column(name = "item_js_path", type = "VARCHAR", length = "200", nullable = "true", comment = "js路径，前端动态引入")
	private String itemJsPath;

	@Column(name = "item_css_path", type = "VARCHAR", length = "200", nullable = "true", comment = "css路径，前端动态引入")
	private String itemCssPath;

	@Column(name = "status", type = "TINYINT", length = "3", nullable = "true", comment = "状态 0未启用 1启用")
	private Byte status;

	@Column(name = "remark", type = "VARCHAR", length = "500", nullable = "true", comment = "")
	private String remark;

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Long getCreateUser() {
		return this.createUser;
	}

	public void setCreateUser(Long createUser) {
		this.createUser = createUser;
	}

	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	public Long getUpdateUser() {
		return this.updateUser;
	}

	public void setUpdateUser(Long updateUser) {
		this.updateUser = updateUser;
	}

	public String getItemName() {
		return this.itemName;
	}

	public void setItemName(String itemName) {
		this.itemName = itemName;
	}

	public Integer getItemIndex() {
		return this.itemIndex;
	}

	public void setItemIndex(Integer itemIndex) {
		this.itemIndex = itemIndex;
	}

	public String getItemInnerHtml() {
		return this.itemInnerHtml;
	}

	public void setItemInnerHtml(String itemInnerHtml) {
		this.itemInnerHtml = itemInnerHtml;
	}

	public String getItemJsPath() {
		return this.itemJsPath;
	}

	public void setItemJsPath(String itemJsPath) {
		this.itemJsPath = itemJsPath;
	}

	public Byte getStatus() {
		return this.status;
	}

	public void setStatus(Byte status) {
		this.status = status;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public String getItemCssPath() {
		return itemCssPath;
	}

	public void setItemCssPath(String itemCssPath) {
		this.itemCssPath = itemCssPath;
	}

}