package io.github.junxworks.ep.sys.entity;

import io.github.junxworks.ep.core.orm.annotations.Table;
import io.github.junxworks.ep.core.orm.annotations.PrimaryKey;
import io.github.junxworks.ep.core.orm.annotations.Column;
import java.util.Date;

/**
 * <p>Entity Class</p>
 * <p>Table: s_menu</p>
 *
 * @since 2021-1-24 17:46:30 Generated by JunxPlugin
 */
 
@Table(tableName="s_menu",tableComment="")
public class SMenu {
	
    @PrimaryKey
    @Column(name="id", type="BIGINT", length="19", nullable="false", comment="菜单编号")
    private Long id;
    
    @Column(name="parentId", type="BIGINT", length="19", nullable="true", comment="上级菜单编号")
    private Long parentId;	
    
    @Column(name="name", type="VARCHAR", length="255", nullable="true", comment="菜单名称")
    private String name;	
    
    @Column(name="type", type="TINYINT", length="3", nullable="true", comment="类型 0菜单 1按钮 2目录 ")
    private Byte type;	
    
    @Column(name="mark", type="LONGVARCHAR", length="65,535", nullable="true", comment="菜单标记")
    private String mark;	
    
    @Column(name="url", type="LONGVARCHAR", length="65,535", nullable="true", comment="菜单链接")
    private String url;	
    
    @Column(name="icon", type="VARCHAR", length="255", nullable="true", comment="菜单图标")
    private String icon;	
    
    @Column(name="sort", type="TINYINT", length="3", nullable="true", comment="排序")
    private Byte sort;	
    
    @Column(name="status", type="TINYINT", length="3", nullable="true", comment="状态 -1已删除 0正常")
    private Byte status;	
    
    @Column(name="createUser", type="BIGINT", length="19", nullable="true", comment="创建人编号")
    private Long createUser;	
    
    @Column(name="createTime", type="TIMESTAMP", length="19", nullable="true", comment="创建日期")
    private Date createTime;	
    
    @Column(name="updateUser", type="BIGINT", length="19", nullable="true", comment="修改人编号")
    private Long updateUser;	
    
    @Column(name="updateTime", type="TIMESTAMP", length="19", nullable="true", comment="修改日期")
    private Date updateTime;	
    

    public Long getId(){
        return this.id;
    }

    public void setId(Long id){
        this.id = id;
    }

    public Long getParentId(){
        return this.parentId;
    }

    public void setParentId(Long parentId){
        this.parentId = parentId;
    }
    public String getName(){
        return this.name;
    }

    public void setName(String name){
        this.name = name;
    }
    public Byte getType(){
        return this.type;
    }

    public void setType(Byte type){
        this.type = type;
    }
    public String getMark(){
        return this.mark;
    }

    public void setMark(String mark){
        this.mark = mark;
    }
    public String getUrl(){
        return this.url;
    }

    public void setUrl(String url){
        this.url = url;
    }
    public String getIcon(){
        return this.icon;
    }

    public void setIcon(String icon){
        this.icon = icon;
    }
    public Byte getSort(){
        return this.sort;
    }

    public void setSort(Byte sort){
        this.sort = sort;
    }
    public Byte getStatus(){
        return this.status;
    }

    public void setStatus(Byte status){
        this.status = status;
    }
    public Long getCreateUser(){
        return this.createUser;
    }

    public void setCreateUser(Long createUser){
        this.createUser = createUser;
    }
    public Date getCreateTime(){
        return this.createTime;
    }

    public void setCreateTime(Date createTime){
        this.createTime = createTime;
    }
    public Long getUpdateUser(){
        return this.updateUser;
    }

    public void setUpdateUser(Long updateUser){
        this.updateUser = updateUser;
    }
    public Date getUpdateTime(){
        return this.updateTime;
    }

    public void setUpdateTime(Date updateTime){
        this.updateTime = updateTime;
    }
}