package io.github.junxworks.ep.sys.entity;

import io.github.junxworks.ep.core.orm.annotations.Table;
import io.github.junxworks.ep.core.orm.annotations.PrimaryKey;
import io.github.junxworks.ep.core.orm.annotations.Column;
import java.util.Date;

/**
 * <p>Entity Class</p>
 * <p>Table: s_param</p>
 *
 * @since 2021-2-19 15:18:04 Generated by JunxPlugin
 */
 
@Table(tableName="s_param",tableComment="")
public class SParam {
	
    @PrimaryKey
    @Column(name="id", type="BIGINT", length="19", nullable="false", comment="编号")
    private Long id;
    
    @Column(name="create_user", type="BIGINT", length="19", nullable="true", comment="创建人编号")
    private Long createUser;	
    
    @Column(name="create_time", type="TIMESTAMP", length="19", nullable="true", comment="创建日期")
    private Date createTime;	
    
    @Column(name="update_user", type="BIGINT", length="19", nullable="true", comment="修改人编号")
    private Long updateUser;	
    
    @Column(name="update_time", type="TIMESTAMP", length="19", nullable="true", comment="修改日期")
    private Date updateTime;	
    
    @Column(name="status", type="TINYINT", length="3", nullable="true", comment="状态 -1已删除 0正常")
    private Byte status;	
    
    @Column(name="param_name", type="VARCHAR", length="50", nullable="true", comment="参数名")
    private String paramName;	
    
    @Column(name="param_value", type="VARCHAR", length="500", nullable="true", comment="参数值")
    private String paramValue;	
    
    @Column(name="remark", type="VARCHAR", length="200", nullable="true", comment="备注")
    private String remark;	
    
    @Column(name="param_group", type="VARCHAR", length="50", nullable="true", comment="分组")
    private String paramGroup;	
    

    public Long getId(){
        return this.id;
    }

    public void setId(Long id){
        this.id = id;
    }

    public Long getCreateUser(){
        return this.createUser;
    }

    public void setCreateUser(Long createUser){
        this.createUser = createUser;
    }
    public Date getCreateTime(){
        return this.createTime;
    }

    public void setCreateTime(Date createTime){
        this.createTime = createTime;
    }
    public Long getUpdateUser(){
        return this.updateUser;
    }

    public void setUpdateUser(Long updateUser){
        this.updateUser = updateUser;
    }
    public Date getUpdateTime(){
        return this.updateTime;
    }

    public void setUpdateTime(Date updateTime){
        this.updateTime = updateTime;
    }
    public Byte getStatus(){
        return this.status;
    }

    public void setStatus(Byte status){
        this.status = status;
    }
    public String getParamName(){
        return this.paramName;
    }

    public void setParamName(String paramName){
        this.paramName = paramName;
    }
    public String getParamValue(){
        return this.paramValue;
    }

    public void setParamValue(String paramValue){
        this.paramValue = paramValue;
    }
    public String getRemark(){
        return this.remark;
    }

    public void setRemark(String remark){
        this.remark = remark;
    }
    public String getParamGroup(){
        return this.paramGroup;
    }

    public void setParamGroup(String paramGroup){
        this.paramGroup = paramGroup;
    }
}