package io.github.junxworks.ep.modules.modules.sys.mapper;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

import io.github.junxworks.ep.core.orm.BaseMapper;
import io.github.junxworks.ep.modules.modules.sys.entity.SSqls;

/**
 * <p>Mapper</p>
 * <p>Table: s_dict</p>
 *
 * @since 2019-6-28 15:44:30 Generated by JunxPlugin
 */
@Mapper
public interface DataMapper extends BaseMapper {
	@Select("select * from s_sqls where status=0 and uid=#{uid}")
	SSqls getSqlByUid(@Param("uid") String uid);
}