package io.github.junxworks.ep.modules.modules.sys.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

import com.github.pagehelper.Page;
import io.github.junxworks.ep.core.orm.BaseMapper;
import io.github.junxworks.ep.modules.modules.sys.dto.DictionaryPageable;
import io.github.junxworks.ep.modules.modules.sys.vo.DictionaryInfoVo;

/**
 * <p>Mapper</p>
 * <p>Table: s_dict</p>
 *
 * @since 2019-6-28 15:44:30 Generated by JunxPlugin
 */
@Mapper
public interface DictMapper extends BaseMapper{

	@Select("select * from s_dict where id=#{id}")
	public DictionaryInfoVo selectById(Long id);

	@Delete("delete from s_dict where id=#{id}")
	public int deleteById(Long id);
	@Select("<script>" +
			"select * from s_dict where 1=1" +
			"<if test='status!=null '> " +
			"and status = #{status} " +
			"</if>" +
			"<if test='parentCode!=null and parentCode.length>0 '> " +
			"and parentCode like CONCAT('%',#{parentCode},'%') " +
			"</if>" +
			"<if test='dataValue!=null and dataValue.length>0 '> " +
			"and dataValue like CONCAT('%',#{dataValue},'%')  " +
			"</if>" +
			"<if test='dataCode!=null and dataCode.length>0 '> " +
			"and dataCode =#{dataCode}   " +
			"</if>" +
			" order by parentCode desc,sort asc"+
			"</script>")
	public Page<DictionaryInfoVo> selectAll(DictionaryPageable entity);

	@Select("<script>" +
			"select * from s_dict where 1=1" +
			"<if test='status!=null '> " +
			"and status = #{status} " +
			"</if>" +
			"<if test='parentCode!=null and parentCode.length>0 '> " +
			"and parentCode=#{parentCode} " +
			"</if>" +
			"<if test='dataValue!=null and dataValue.length>0 '> " +
			"and dataValue=#{dataValue}  " +
			"</if>" +
			"<if test='dataCode!=null and dataCode.length>0 '> " +
			"and dataCode =#{dataCode}   " +
			"</if>" +
			" order by parentCode desc,sort asc"+
			"</script>")
	public DictionaryInfoVo selectByCode(DictionaryPageable entity);

	@Select("<script> SELECT * FROM s_dict where 1=1" +
			"<if test='parentCode!=null and parentCode.length>0 '> " +
			"and parentCode=#{parentCode} " +
			"</if>"+
			" GROUP BY parentCode"+ "</script>")
	public List<DictionaryInfoVo> selectParentCode(DictionaryPageable entity);

	@Select("select * from s_dict where parentCode=#{parentCode} and status=0")
	public List<DictionaryInfoVo> selectByParentCode(@Param("parentCode")String parentCode);
	
}