package io.github.junxworks.ep.modules.modules.sys.mapper;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Select;

import com.github.pagehelper.Page;

import io.github.junxworks.ep.core.orm.BaseMapper;
import io.github.junxworks.ep.modules.modules.sys.dto.SystemLogConditionDto;
import io.github.junxworks.ep.modules.modules.sys.vo.SystemLogInfoVo;

/**
 * <p>Mapper</p>
 * <p>Table: s_op_log</p>
 *
 * @since 2019-6-28 15:45:49 Generated by JunxPlugin
 */
@Mapper
public interface OpLogMapper extends BaseMapper{

	@Select("select t.*,u.name from s_op_log t LEFT JOIN s_user u on t.userId=u.id where t.id=#{id}")
	public SystemLogInfoVo selectById(Long id);

	@Delete("delete from s_op_log where id=#{id}")
	public int deleteById(Long id);
	@Select("<script>" +
			"select t.*,u.name from s_op_log t LEFT JOIN s_user u on t.userId=u.id  where 1=1" +
			"<if test='createDate!=null and createDate.length>0 '> " +
			"and TO_DAYS(t.createDate) = TO_DAYS(#{createDate}) " +
			"</if>" +
			"<if test='name!=null and name.length>0 '> " +
			"and u.name like CONCAT('%',#{name},'%') " +
			"</if>" +
			"<if test='opName!=null and opName.length>0 '> " +
			"and t.operation like CONCAT('%',#{opName},'%') " +
			"</if>" +
			" order by t.id desc"+
			"</script>")
	public Page<SystemLogInfoVo> selectAll(SystemLogConditionDto entity);

}