/*
 ***************************************************************************************
 * All rights Reserved, Designed By www.cqhyrc.com.cn
 * @Title:  RoleMenuMapper.java   
 * @Package io.github.junxworks.ep.modules.modules.sys.mapper   
 * @Description: (用一句话描述该文件做什么)   
 * @author: AOC
 * @date:   2019-12-23 9:26:23   
 * @version V1.0 
 * @Copyright: 2019 重庆华宇集团. All rights reserved. 
 * 注意：本内容仅限于公司内部使用，禁止外泄以及用于其他的商业目
 *  ---------------------------------------------------------------------------------- 
 * 文件修改记录
 *     文件版本：         修改人：             修改原因：
 ***************************************************************************************
 */
package io.github.junxworks.ep.modules.modules.sys.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

import io.github.junxworks.ep.core.orm.BaseMapper;

/**
 * <p>Mapper</p>
 * <p>Table: s_role_menu</p>
 *
 * @since 2019-6-28 16:11:25 Generated by JunxPlugin
 */
@Mapper
public interface RoleMenuMapper extends BaseMapper {

	/**
	 * 根据角色ID全量删除关系，用于角色更新
	 *
	 * @param roleId the role id
	 * @return the int
	 */
	@Delete("delete from s_role_menu where roleId=#{roleId}")
	public int deleteByRoleId(Long roleId);

	@Delete({"<script>",
		"delete from s_role_menu where roleId=#{roleId} ",
			"<if test='menuIds!=null'> " +
				" and  menuId not in " +
				"<foreach collection=\"menuIds\" item=\"menuId\" open=\"(\" close=\")\" separator=\",\">" + 
					"#{menuId}" + 
				"</foreach>"+
			"</if>",
		"</script>"})
	public int deleteByMenuIds(@Param("roleId") Long roleId, @Param("menuIds") List<Long> menuIds);
	

	@Select("select menuId from s_role_menu where roleId=#{roleId}")
	public List<Long> queryMenusByRoleId(@Param("roleId") Long roleId);

}