package io.github.junxworks.ep.modules.modules.sys.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

import com.github.pagehelper.Page;
import io.github.junxworks.ep.core.orm.BaseMapper;
import io.github.junxworks.ep.modules.modules.sys.entity.SRole;
import io.github.junxworks.ep.modules.modules.sys.vo.RoleInfoVo;
import io.github.junxworks.ep.modules.modules.sys.vo.UserInfoVo;

/**
 * <p>Mapper</p>
 * <p>Table: s_role</p>
 *
 * @since 2019-6-28 15:46:20 Generated by JunxPlugin
 */
@Mapper
public interface RoleMapper extends BaseMapper{

	@Select("select * from s_role where id=#{id} and status=0")
	SRole selectById(Long id);

	@Select("select r.* from s_role r inner join s_user_role ur on ur.roleId = r.id where r.status=0 and ur.userId=#{userId}")
	List<RoleInfoVo> selectByUserId(Long userId);

	@Select("select * from s_role where roleName=#{roleName} and status=0")
	SRole selectByName(String roleName);

	@Select("select * from s_role where roleTag=#{roleTag} and status=0")
	SRole selectByTag(String roleTag);
	
	@Delete("update s_role set status=-1 where id=#{id}")
	int deleteById(Long id);

	@Select("<script>" +
			"select * from s_role where status=0 " +
			"<if test='query!=null '> " +
				" and roleName like CONCAT('%',#{query},'%') " +
			"</if>" +
			"</script>")
	Page<RoleInfoVo> selectAll(@Param("query") String query);

	@Select("select distinct u.* from s_role r,s_user_role ur,s_user u where ur.roleId = r.id and r.status=0 and ur.userId=u.id and u.status=0 and r.roleTag=#{roleTag}")
	List<UserInfoVo> findUserListByRoleTag(@Param("roleTag")String roleTag);
}