package io.github.junxworks.ep.modules.modules.sys.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Select;

import io.github.junxworks.ep.core.orm.BaseMapper;
import io.github.junxworks.ep.modules.modules.sys.entity.SUserRole;

/**
 * <p>Mapper</p>
 * <p>Table: s_user_role</p>
 *
 * @since 2019-6-28 16:12:03 Generated by JunxPlugin
 */
@Mapper
public interface UserRoleMapper extends BaseMapper{

	@Select("select * from s_user_role where id=#{id}")
	public SUserRole selectById(Long id);

	@Select("select * from s_user_role where userId=#{userId}")
	List<SUserRole> selectByUserId(Long userId);

	@Delete("delete from s_user_role where id=#{id}")
	public int deleteById(Long id);

	@Delete("delete from s_user_role where userId=#{userId}")
	int deleteByUserId(Long userId);


}