package io.github.junxworks.ep.modules.modules.sys.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

import com.github.pagehelper.Page;
import io.github.junxworks.ep.core.orm.BaseMapper;
import io.github.junxworks.ep.modules.modules.sys.dto.UserPageable;
import io.github.junxworks.ep.modules.modules.sys.entity.SUser;
import io.github.junxworks.ep.modules.modules.sys.vo.UserInfoVo;

/**
 * <p>Mapper</p>
 * <p>Table: s_user</p>
 *
 * @since 2019-6-28 16:11:42 Generated by JunxPlugin
 */
@Mapper
public interface UserMapper extends BaseMapper{

	@Update(
			"<script>"
					+"update s_user set "
					+ " status=#{status}"
					+ " where id=#{userId}"
					+ "</script>"
	)
	public int updateUserStatus(@Param("userId")Long userId,@Param("status")Byte status);

	@Update(
			"<script>"
					+"update s_user set "
					+ " password=#{password}"
					+ " where id=#{userId}"
					+ "</script>"
	)
	int updateUserPass(@Param("userId")Long userId,@Param("password")String password);

	@Select("select s.*,o.orgName from s_user s left join s_org o on s.orgNo=o.orgNo and o.status=0 where s.id=#{id}")
	UserInfoVo selectById(Long id);

	@Select("select * from s_user where userName=#{userName} and status=0")
	SUser selectByUserName(String mobile);

	@Delete("delete from s_user where id=#{id}")
	int deleteById(Long id);

	@Select("<script>" +
			"SELECT u.*, o.orgName,r.roleName " + 
			"FROM s_user u " + 
			"     LEFT JOIN s_org o ON u.orgNo = o.orgNo AND o.status = 0 " + 
			"     LEFT JOIN (SELECT ur.userId, group_concat(r.roleName) roleName " + 
			"                FROM s_user_role ur, s_role r " + 
			"                WHERE ur.roleId = r.id AND r.status = 0 group by ur.userId) r " + 
			"        ON u.id = r.userId" +
			"<if test='roleIds!=null'> " +
				",s_user_role ur"+
			"</if>"+
			" where 1=1 "+ 
			"<if test='query!=null and query.length>0'> " +
			"     and (u.name like CONCAT('%',#{query},'%') or u.mobile = #{query}) " +
			"</if>" +
			"<if test='orgNo!=null and orgNo.length>0'> " +
			"     and u.orgNo=#{orgNo} " +
			"</if>" +
			"<if test='roleIds!=null'> " +
				" and u.id=ur.userId"+ 
			    " and ur.roleId in " +
				"<foreach collection=\"roleIds\" item=\"roleId\" open=\"(\" close=\")\" separator=\",\">" + 
					"#{roleId}" + 
				"</foreach>"+
			"</if>"+
			" order by u.id asc"+
			"</script>")
	Page<UserInfoVo> selectAll(UserPageable condition);

	@Select("<script>" +
			"SELECT DISTINCT u.* from s_user u,s_user_role ur,s_role r,s_role_menu rm,s_menu m "
			+ " where u.status=0 "
			+ " and r.status=0 "
			+ " and m.status=0 "
			+ " and u.id=ur.userId "
			+ " and ur.roleId = r.id "
			+ " and r.id=rm.roleId "
			+ " and rm.menuId=m.id "+
			"<if test='auth!=null '> " +
			" and m.mark=#{auth} " +
			"</if>" +
			"</script>")
	Page<UserInfoVo> getUserListByAuth(@Param("auth") String auth);
	 
	@Select({"SELECT DISTINCT u.* from s_user u,s_user_role ur,s_role r where r.id=#{id} and r.status = 0 and r.id=ur.roleId and ur.userId=u.id and u.status=0 order by u.id asc"})
	List<UserInfoVo> getUserListByRoleId(@Param("id")Long roleId);
	
	@Select({"SELECT DISTINCT u.* from s_user u,s_user_role ur,s_role r where r.roleTag=#{tag} and r.status = 0 and r.id=ur.roleId and ur.userId=u.id and u.status=0 order by u.id asc"})
	List<UserInfoVo> getUserListByRoleTag(@Param("tag")String roleTag);

}