/*
 ***************************************************************************************
 * EP for web developers.Supported By Junxworks
 * @Title:  SJob.java   
 * @Package io.github.junxworks.ep.scheduler.entity   
 * @Description: (用一句话描述该文件做什么)   
 * @author: Administrator
 * @date:   2021-1-24 17:50:25   
 * @version V1.0 
 * @Copyright: 2021 Junxworks. All rights reserved. 
 * 注意：
 *  ---------------------------------------------------------------------------------- 
 * 文件修改记录
 *     文件版本：         修改人：             修改原因：
 ***************************************************************************************
 */
package io.github.junxworks.ep.scheduler.entity;

import io.github.junxworks.ep.core.orm.annotations.Table;
import io.github.junxworks.ep.core.orm.annotations.PrimaryKey;
import io.github.junxworks.ep.core.orm.annotations.Column;
import java.util.Date;

/**
 * <p>Entity Class</p>
 * <p>Table: s_job</p>
 *
 * @since 2021-1-24 17:47:40 Generated by JunxPlugin
 */
 
@Table(tableName="s_job",tableComment="")
public class SJob {
	
    @PrimaryKey
    @Column(name="id", type="BIGINT", length="19", nullable="false", comment="任务id")
    private Long id;
    
    @Column(name="jobName", type="VARCHAR", length="100", nullable="true", comment="任务名称")
    private String jobName;	
    
    @Column(name="beanName", type="VARCHAR", length="200", nullable="true", comment="spring bean名称")
    private String beanName;	
    
    @Column(name="methodName", type="VARCHAR", length="100", nullable="true", comment="方法名")
    private String methodName;	
    
    @Column(name="params", type="VARCHAR", length="2,000", nullable="true", comment="参数")
    private String params;	
    
    @Column(name="cronExpression", type="VARCHAR", length="100", nullable="true", comment="cron表达式")
    private String cronExpression;	
    
    @Column(name="status", type="TINYINT", length="3", nullable="true", comment="任务状态  0：正常  1：暂停")
    private Byte status;	
    
    @Column(name="remark", type="VARCHAR", length="255", nullable="true", comment="任务备注")
    private String remark;	
    
    @Column(name="createUser", type="BIGINT", length="19", nullable="true", comment="创建人编号")
    private Long createUser;	
    
    @Column(name="createTime", type="TIMESTAMP", length="19", nullable="true", comment="创建日期")
    private Date createTime;	
    
    @Column(name="updateUser", type="BIGINT", length="19", nullable="true", comment="修改人编号")
    private Long updateUser;	
    
    @Column(name="updateTime", type="TIMESTAMP", length="19", nullable="true", comment="修改日期")
    private Date updateTime;	
    

    public Long getId(){
        return this.id;
    }

    public void setId(Long id){
        this.id = id;
    }

    public String getJobName(){
        return this.jobName;
    }

    public void setJobName(String jobName){
        this.jobName = jobName;
    }
    public String getBeanName(){
        return this.beanName;
    }

    public void setBeanName(String beanName){
        this.beanName = beanName;
    }
    public String getMethodName(){
        return this.methodName;
    }

    public void setMethodName(String methodName){
        this.methodName = methodName;
    }
    public String getParams(){
        return this.params;
    }

    public void setParams(String params){
        this.params = params;
    }
    public String getCronExpression(){
        return this.cronExpression;
    }

    public void setCronExpression(String cronExpression){
        this.cronExpression = cronExpression;
    }
    public Byte getStatus(){
        return this.status;
    }

    public void setStatus(Byte status){
        this.status = status;
    }
    public String getRemark(){
        return this.remark;
    }

    public void setRemark(String remark){
        this.remark = remark;
    }
    public Long getCreateUser(){
        return this.createUser;
    }

    public void setCreateUser(Long createUser){
        this.createUser = createUser;
    }
    public Date getCreateTime(){
        return this.createTime;
    }

    public void setCreateTime(Date createTime){
        this.createTime = createTime;
    }
    public Long getUpdateUser(){
        return this.updateUser;
    }

    public void setUpdateUser(Long updateUser){
        this.updateUser = updateUser;
    }
    public Date getUpdateTime(){
        return this.updateTime;
    }

    public void setUpdateTime(Date updateTime){
        this.updateTime = updateTime;
    }
}