package io.github.junxworks.ep.scheduler.entity;

import io.github.junxworks.ep.core.orm.annotations.Table;
import io.github.junxworks.ep.core.orm.annotations.PrimaryKey;
import io.github.junxworks.ep.core.orm.annotations.Column;
import java.util.Date;

/**
 * <p>Entity Class</p>
 * <p>Table: s_job_log</p>
 *
 * @since 2021-2-19 15:34:38 Generated by JunxPlugin
 */
 
@Table(tableName="s_job_log",tableComment="")
public class SJobLog {
	
    @PrimaryKey
    @Column(name="id", type="BIGINT", length="19", nullable="false", comment="任务日志id")
    private Long id;
    
    @Column(name="job_id", type="BIGINT", length="19", nullable="false", comment="任务id")
    private Long jobId;	
    
    @Column(name="bean_name", type="VARCHAR", length="200", nullable="true", comment="spring bean名称")
    private String beanName;	
    
    @Column(name="method_name", type="VARCHAR", length="100", nullable="true", comment="方法名")
    private String methodName;	
    
    @Column(name="params", type="VARCHAR", length="2,000", nullable="true", comment="参数")
    private String params;	
    
    @Column(name="status", type="TINYINT", length="3", nullable="false", comment="任务状态    0：成功    1：失败")
    private Byte status;	
    
    @Column(name="error", type="VARCHAR", length="2,000", nullable="true", comment="失败信息")
    private String error;	
    
    @Column(name="costs", type="INTEGER", length="10", nullable="false", comment="耗时(单位：毫秒)")
    private Integer costs;	
    
    @Column(name="create_time", type="TIMESTAMP", length="19", nullable="true", comment="创建时间")
    private Date createTime;	
    

    public Long getId(){
        return this.id;
    }

    public void setId(Long id){
        this.id = id;
    }

    public Long getJobId(){
        return this.jobId;
    }

    public void setJobId(Long jobId){
        this.jobId = jobId;
    }
    public String getBeanName(){
        return this.beanName;
    }

    public void setBeanName(String beanName){
        this.beanName = beanName;
    }
    public String getMethodName(){
        return this.methodName;
    }

    public void setMethodName(String methodName){
        this.methodName = methodName;
    }
    public String getParams(){
        return this.params;
    }

    public void setParams(String params){
        this.params = params;
    }
    public Byte getStatus(){
        return this.status;
    }

    public void setStatus(Byte status){
        this.status = status;
    }
    public String getError(){
        return this.error;
    }

    public void setError(String error){
        this.error = error;
    }
    public Integer getCosts(){
        return this.costs;
    }

    public void setCosts(Integer costs){
        this.costs = costs;
    }
    public Date getCreateTime(){
        return this.createTime;
    }

    public void setCreateTime(Date createTime){
        this.createTime = createTime;
    }
}