package io.github.junxworks.ep.codegen.entity;

import io.github.junxworks.ep.core.orm.annotations.Table;
import io.github.junxworks.ep.core.orm.annotations.PrimaryKey;
import io.github.junxworks.ep.core.orm.annotations.Column;
import java.util.Date;

/**
 * <p>Entity Class</p>
 * <p>Table: ep_cg_template</p>
 *
 * @since 2021年11月7日下午9:58:12 Generated by JunxPlugin
 */
 
@Table(tableName="ep_cg_template",tableComment="")
public class EpCgTemplate {
	
    @PrimaryKey
    @Column(name="id", type="BIGINT", length="19", nullable="false", comment="")
    private Long id;
    
    @Column(name="create_user", type="BIGINT", length="19", nullable="true", comment="创建人员")
    private Long createUser;	
    
    @Column(name="create_time", type="TIMESTAMP", length="19", nullable="true", comment="创建时间")
    private Date createTime;	
    
    @Column(name="update_user", type="BIGINT", length="19", nullable="true", comment="修改人员")
    private Long updateUser;	
    
    @Column(name="update_time", type="TIMESTAMP", length="19", nullable="true", comment="修改时间")
    private Date updateTime;	
    
    @Column(name="tmp_id", type="VARCHAR", length="100", nullable="false", comment="模板标识")
    private String tmpId;	
    
    @Column(name="tmp_desc", type="VARCHAR", length="100", nullable="true", comment="模板描述")
    private String tmpDesc;	
    
    @Column(name="output_name", type="VARCHAR", length="100", nullable="false", comment="输出文件名称")
    private String outputName;	
    
    @Column(name="content", type="LONGVARCHAR", length="65,535", nullable="false", comment="模板内容")
    private String content;	
    
    @Column(name="status", type="TINYINT", length="3", nullable="true", comment="0正常 -1删除")
    private Byte status;	
    

    public Long getId(){
        return this.id;
    }

    public void setId(Long id){
        this.id = id;
    }

    public Long getCreateUser(){
        return this.createUser;
    }

    public void setCreateUser(Long createUser){
        this.createUser = createUser;
    }
    public Date getCreateTime(){
        return this.createTime;
    }

    public void setCreateTime(Date createTime){
        this.createTime = createTime;
    }
    public Long getUpdateUser(){
        return this.updateUser;
    }

    public void setUpdateUser(Long updateUser){
        this.updateUser = updateUser;
    }
    public Date getUpdateTime(){
        return this.updateTime;
    }

    public void setUpdateTime(Date updateTime){
        this.updateTime = updateTime;
    }
    public String getTmpId(){
        return this.tmpId;
    }

    public void setTmpId(String tmpId){
        this.tmpId = tmpId;
    }
    public String getTmpDesc(){
        return this.tmpDesc;
    }

    public void setTmpDesc(String tmpDesc){
        this.tmpDesc = tmpDesc;
    }
    public String getOutputName(){
        return this.outputName;
    }

    public void setOutputName(String outputName){
        this.outputName = outputName;
    }
    public String getContent(){
        return this.content;
    }

    public void setContent(String content){
        this.content = content;
    }
    public Byte getStatus(){
        return this.status;
    }

    public void setStatus(Byte status){
        this.status = status;
    }
}