package io.github.junxworks.ep.codegen.entity;

import io.github.junxworks.ep.core.orm.annotations.Table;
import io.github.junxworks.ep.core.orm.annotations.PrimaryKey;
import io.github.junxworks.ep.core.orm.annotations.Column;
import java.util.Date;

/**
 * <p>Entity Class</p>
 * <p>Table: ep_cg_generator</p>
 *
 * @since 2021年11月9日下午9:51:54 Generated by JunxPlugin
 */

@Table(tableName = "ep_cg_generator", tableComment = "")
public class EpCgGenerator {

	@PrimaryKey
	@Column(name = "id", type = "BIGINT", length = "19", nullable = "false", comment = "")
	private Long id;

	@Column(name = "create_user", type = "BIGINT", length = "19", nullable = "true", comment = "创建人员")
	private Long createUser;

	@Column(name = "create_time", type = "TIMESTAMP", length = "19", nullable = "true", comment = "创建时间")
	private Date createTime;

	@Column(name = "update_user", type = "BIGINT", length = "19", nullable = "true", comment = "修改人员")
	private Long updateUser;

	@Column(name = "update_time", type = "TIMESTAMP", length = "19", nullable = "true", comment = "修改时间")
	private Date updateTime;

	@Column(name = "gen_name", type = "VARCHAR", length = "100", nullable = "false", comment = "生成器标识")
	private String genName;

	@Column(name = "gen_desc", type = "VARCHAR", length = "200", nullable = "true", comment = "生成器描述")
	private String genDesc;

	@Column(name = "templates", type = "VARCHAR", length = "1,000", nullable = "false", comment = "关联模板")
	private String templates;

	@Column(name = "status", type = "TINYINT", length = "3", nullable = "true", comment = "0正常 -1删除")
	private Byte status;

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Long getCreateUser() {
		return this.createUser;
	}

	public void setCreateUser(Long createUser) {
		this.createUser = createUser;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Long getUpdateUser() {
		return this.updateUser;
	}

	public void setUpdateUser(Long updateUser) {
		this.updateUser = updateUser;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public String getGenName() {
		return genName;
	}

	public void setGenName(String genName) {
		this.genName = genName;
	}

	public String getGenDesc() {
		return this.genDesc;
	}

	public void setGenDesc(String genDesc) {
		this.genDesc = genDesc;
	}

	public String getTemplates() {
		return this.templates;
	}

	public void setTemplates(String templates) {
		this.templates = templates;
	}

	public Byte getStatus() {
		return this.status;
	}

	public void setStatus(Byte status) {
		this.status = status;
	}
}