package io.github.junxworks.ep.codegen.entity;

import io.github.junxworks.ep.core.orm.annotations.Table;
import io.github.junxworks.ep.core.orm.annotations.PrimaryKey;
import io.github.junxworks.ep.core.orm.annotations.Column;
import java.util.Date;

/**
 * <p>Entity Class</p>
 * <p>Table: ep_cg_datasource</p>
 *
 * @since 2021年10月31日下午10:31:59 Generated by JunxPlugin
 */

@Table(tableName = "ep_cg_datasource", tableComment = "")
public class EpCgDatasource {

	@PrimaryKey
	@Column(name = "id", type = "BIGINT", length = "19", nullable = "false", comment = "")
	private Long id;

	@Column(name = "create_user", type = "BIGINT", length = "19", nullable = "true", comment = "创建人员")
	private Long createUser;

	@Column(name = "create_time", type = "TIMESTAMP", length = "19", nullable = "true", comment = "创建时间")
	private Date createTime;

	@Column(name = "update_user", type = "BIGINT", length = "19", nullable = "true", comment = "")
	private Long updateUser;

	@Column(name = "update_time", type = "TIMESTAMP", length = "19", nullable = "true", comment = "")
	private Date updateTime;

	@Column(name = "ds_id", type = "VARCHAR", length = "100", nullable = "false", comment = "数据源名称")
	private String dsId;

	@Column(name = "ds_desc", type = "VARCHAR", length = "100", nullable = "true", comment = "数据源描述")
	private String dsDesc;

	@Column(name = "db_type", type = "VARCHAR", length = "50", nullable = "false", comment = "数据库类型")
	private String dbType;

	@Column(name = "conn_url", type = "VARCHAR", length = "200", nullable = "false", comment = "连接地址")
	private String connUrl;

	@Column(name = "db_name", type = "VARCHAR", length = "50", nullable = "false", comment = "数据库实例名")
	private String dbName;

	@Column(name = "db_username", type = "VARCHAR", length = "50", nullable = "false", comment = "数据库账号")
	private String dbUsername;

	@Column(name = "db_passwd", type = "VARCHAR", length = "200", nullable = "false", comment = "数据库密码")
	private String dbPasswd;

	@Column(name = "status", type = "TINYINT", length = "3", nullable = "true", comment = "0正常 -1删除")
	private Byte status;

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Long getCreateUser() {
		return this.createUser;
	}

	public void setCreateUser(Long createUser) {
		this.createUser = createUser;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Long getUpdateUser() {
		return this.updateUser;
	}

	public void setUpdateUser(Long updateUser) {
		this.updateUser = updateUser;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public String getDsId() {
		return this.dsId;
	}

	public void setDsId(String dsId) {
		this.dsId = dsId;
	}

	public String getDsDesc() {
		return this.dsDesc;
	}

	public void setDsDesc(String dsDesc) {
		this.dsDesc = dsDesc;
	}

	public String getDbType() {
		return this.dbType;
	}

	public void setDbType(String dbType) {
		this.dbType = dbType;
	}

	public String getConnUrl() {
		return this.connUrl;
	}

	public void setConnUrl(String connUrl) {
		this.connUrl = connUrl;
	}

	public String getDbName() {
		return dbName;
	}

	public void setDbName(String dbName) {
		this.dbName = dbName;
	}

	public String getDbUsername() {
		return this.dbUsername;
	}

	public void setDbUsername(String dbUsername) {
		this.dbUsername = dbUsername;
	}

	public String getDbPasswd() {
		return this.dbPasswd;
	}

	public void setDbPasswd(String dbPasswd) {
		this.dbPasswd = dbPasswd;
	}

	public Byte getStatus() {
		return this.status;
	}

	public void setStatus(Byte status) {
		this.status = status;
	}
}