package io.github.junxworks.ep.modules.modules.sys.dto;

import io.github.junxworks.ep.core.orm.annotations.Table;
import io.github.junxworks.ep.core.orm.annotations.PrimaryKey;
import io.github.junxworks.ep.core.orm.annotations.Column;
import java.util.Date;

/**
 * <p>Entity Class</p>
 * <p>Table: s_org</p>
 *
 * @since 2019-12-12 17:16:46 Generated by JunxPlugin
 */
 
@Table(tableName="s_org",tableComment="")
public class OrgDto {
	
    @PrimaryKey
    @Column(name="id", type="BIGINT", length="19", nullable="false", comment="编号")
    private Long id;
    
    @Column(name="creatorId", type="BIGINT", length="19", nullable="true", comment="创建人编号")
    private Long creatorId;	
    
    @Column(name="createDate", type="TIMESTAMP", length="19", nullable="true", comment="创建日期")
    private Date createDate;	
    
    @Column(name="modifierId", type="BIGINT", length="19", nullable="true", comment="修改人编号")
    private Long modifierId;	
    
    @Column(name="modifyDate", type="TIMESTAMP", length="19", nullable="true", comment="修改日期")
    private Date modifyDate;	
    
    @Column(name="status", type="TINYINT", length="3", nullable="true", comment="状态 -1已删除 0正常")
    private Byte status;	
    
    @Column(name="orgNo", type="VARCHAR", length="50", nullable="true", comment="组织编码")
    private String orgNo;	
    
    @Column(name="orgName", type="VARCHAR", length="100", nullable="true", comment="组织名称")
    private String orgName;	
    
    @Column(name="orgType", type="VARCHAR", length="20", nullable="true", comment="机构类型 参考码表机构类型 orgType")
    private String orgType;	
    
    @Column(name="parentNo", type="VARCHAR", length="50", nullable="true", comment="直接上级机构编码")
    private String parentNo;	
    
    @Column(name="topLevelNo", type="VARCHAR", length="50", nullable="true", comment="顶级机构编码")
    private String topLevelNo;	
    
    @Column(name="orgPath", type="VARCHAR", length="200", nullable="true", comment="组织路径")
    private String orgPath;	
    
    @Column(name="remark", type="VARCHAR", length="200", nullable="true", comment="备注")
    private String remark;	
    

    public Long getId(){
        return this.id;
    }

    public void setId(Long id){
        this.id = id;
    }

    public Long getCreatorId(){
        return this.creatorId;
    }

    public void setCreatorId(Long creatorId){
        this.creatorId = creatorId;
    }
    public Date getCreateDate(){
        return this.createDate;
    }

    public void setCreateDate(Date createDate){
        this.createDate = createDate;
    }
    public Long getModifierId(){
        return this.modifierId;
    }

    public void setModifierId(Long modifierId){
        this.modifierId = modifierId;
    }
    public Date getModifyDate(){
        return this.modifyDate;
    }

    public void setModifyDate(Date modifyDate){
        this.modifyDate = modifyDate;
    }
    public Byte getStatus(){
        return this.status;
    }

    public void setStatus(Byte status){
        this.status = status;
    }
    public String getOrgNo(){
        return this.orgNo;
    }

    public void setOrgNo(String orgNo){
        this.orgNo = orgNo;
    }
    public String getOrgName(){
        return this.orgName;
    }

    public void setOrgName(String orgName){
        this.orgName = orgName;
    }
    public String getOrgType(){
        return this.orgType;
    }

    public void setOrgType(String orgType){
        this.orgType = orgType;
    }
    public String getParentNo(){
        return this.parentNo;
    }

    public void setParentNo(String parentNo){
        this.parentNo = parentNo;
    }
    public String getTopLevelNo(){
        return this.topLevelNo;
    }

    public void setTopLevelNo(String topLevelNo){
        this.topLevelNo = topLevelNo;
    }
    public String getOrgPath(){
        return this.orgPath;
    }

    public void setOrgPath(String orgPath){
        this.orgPath = orgPath;
    }
    public String getRemark(){
        return this.remark;
    }

    public void setRemark(String remark){
        this.remark = remark;
    }
}