package io.github.junxworks.ep.codegen.dto;

import java.util.Date;

/**
 * <p>Entity Class</p>
 * <p>Table: ep_cg_template</p>
 *
 * @since 2021年11月7日下午9:58:12 Generated by JunxPlugin
 */

public class EpCgTemplateDto {

	private Long id;

	private Long createUser;

	private Date createTime;

	private Long updateUser;

	private Date updateTime;

	private String tmpId;

	private String tmpDesc;

	private String outputName;

	private String content;

	private Byte status;

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Long getCreateUser() {
		return this.createUser;
	}

	public void setCreateUser(Long createUser) {
		this.createUser = createUser;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Long getUpdateUser() {
		return this.updateUser;
	}

	public void setUpdateUser(Long updateUser) {
		this.updateUser = updateUser;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public String getTmpId() {
		return this.tmpId;
	}

	public void setTmpId(String tmpId) {
		this.tmpId = tmpId;
	}

	public String getTmpDesc() {
		return this.tmpDesc;
	}

	public void setTmpDesc(String tmpDesc) {
		this.tmpDesc = tmpDesc;
	}

	public String getOutputName() {
		return this.outputName;
	}

	public void setOutputName(String outputName) {
		this.outputName = outputName;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public Byte getStatus() {
		return this.status;
	}

	public void setStatus(Byte status) {
		this.status = status;
	}
}