package io.github.junxworks.ep.codegen.dto;

import java.util.Date;
import java.util.List;

import io.github.junxworks.ep.sys.dto.TransferDto;

/**
 * <p>Entity Class</p>
 * <p>Table: ep_cg_generator</p>
 *
 * @since 2021年11月9日下午9:51:54 Generated by JunxPlugin
 */

public class EpCgGeneratorDto {

	private Long id;

	private Long createUser;

	private Date createTime;

	private Long updateUser;

	private Date updateTime;

	private String genName;

	private String genDesc;

	private String templates;

	private Byte status;

	private List<TransferDto> templateList;

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Long getCreateUser() {
		return this.createUser;
	}

	public void setCreateUser(Long createUser) {
		this.createUser = createUser;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Long getUpdateUser() {
		return this.updateUser;
	}

	public void setUpdateUser(Long updateUser) {
		this.updateUser = updateUser;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public String getGenName() {
		return genName;
	}

	public void setGenName(String genName) {
		this.genName = genName;
	}

	public String getGenDesc() {
		return this.genDesc;
	}

	public void setGenDesc(String genDesc) {
		this.genDesc = genDesc;
	}

	public String getTemplates() {
		return this.templates;
	}

	public void setTemplates(String templates) {
		this.templates = templates;
	}

	public Byte getStatus() {
		return this.status;
	}

	public void setStatus(Byte status) {
		this.status = status;
	}

	public List<TransferDto> getTemplateList() {
		return templateList;
	}

	public void setTemplateList(List<TransferDto> templateList) {
		this.templateList = templateList;
	}

}