package io.github.junxworks.ep.codegen.dto;

/**
 * <p>Entity Class</p>
 * <p>Table: ep_cg_generator</p>
 *
 * @since 2021年11月9日下午9:51:54 Generated by JunxPlugin
 */

public class FileGenerateCondition {

	private Long genId;

	private String dsId;

	private String tables;

	public Long getGenId() {
		return genId;
	}

	public void setGenId(Long genId) {
		this.genId = genId;
	}

	public String getDsId() {
		return dsId;
	}

	public void setDsId(String dsId) {
		this.dsId = dsId;
	}

	public String getTables() {
		return tables;
	}

	public void setTables(String tables) {
		this.tables = tables;
	}

}