package io.github.junxworks.ep.codegen.dto;

/**
 * <p>Entity Class</p>
 * <p>Table: ep_cg_generator</p>
 *
 * @since 2021年11月9日下午9:51:54 Generated by JunxPlugin
 */

public class TableListCondition {

	private String tableName;

	private String dsId;

	public String getTableName() {
		return tableName;
	}

	public void setTableName(String tableName) {
		this.tableName = tableName;
	}

	public String getDsId() {
		return dsId;
	}

	public void setDsId(String dsId) {
		this.dsId = dsId;
	}

}