package io.github.junxworks.ep.modules.modules.sys.entity;

import io.github.junxworks.ep.core.orm.annotations.Table;
import io.github.junxworks.ep.core.orm.annotations.PrimaryKey;
import io.github.junxworks.ep.core.orm.annotations.Column;
import java.util.Date;

/**
 * <p>Entity Class</p>
 * <p>Table: s_op_log</p>
 *
 * @since 2019-6-28 15:42:33 Generated by JunxPlugin
 */
 
@Table(tableName="s_op_log",tableComment="")
public class SOpLog {
	
    @PrimaryKey
    @Column(name="id", type="BIGINT", length="19", nullable="false", comment="编号")
    private Long id;
    
    @Column(name="userId", type="BIGINT", length="19", nullable="true", comment="用户编号")
    private Long userId;	
    
    @Column(name="operation", type="VARCHAR", length="255", nullable="true", comment="操作名称")
    private String operation;	
    
    @Column(name="url", type="LONGVARCHAR", length="65,535", nullable="true", comment="日志url")
    private String url;	
    
    @Column(name="ip", type="VARCHAR", length="255", nullable="true", comment="日志ip")
    private String ip;	
    
    @Column(name="data", type="LONGVARCHAR", length="65,535", nullable="true", comment="请求数据")
    private String data;	
    
    @Column(name="method", type="LONGVARCHAR", length="65,535", nullable="true", comment="请求方法")
    private String method;	
    
    @Column(name="cost", type="BIGINT", length="19", nullable="true", comment="执行耗时")
    private Long cost;	
    
    @Column(name="createDate", type="TIMESTAMP", length="19", nullable="true", comment="创建日期")
    private Date createDate;	
    

    public Long getId(){
        return this.id;
    }

    public void setId(Long id){
        this.id = id;
    }

    public Long getUserId(){
        return this.userId;
    }

    public void setUserId(Long userId){
        this.userId = userId;
    }
    public String getOperation(){
        return this.operation;
    }

    public void setOperation(String operation){
        this.operation = operation;
    }
    public String getUrl(){
        return this.url;
    }

    public void setUrl(String url){
        this.url = url;
    }
    public String getIp(){
        return this.ip;
    }

    public void setIp(String ip){
        this.ip = ip;
    }
    public String getData(){
        return this.data;
    }

    public void setData(String data){
        this.data = data;
    }
    public String getMethod(){
        return this.method;
    }

    public void setMethod(String method){
        this.method = method;
    }
    public Long getCost(){
        return this.cost;
    }

    public void setCost(Long cost){
        this.cost = cost;
    }
    public Date getCreateDate(){
        return this.createDate;
    }

    public void setCreateDate(Date createDate){
        this.createDate = createDate;
    }
}